export const products = [
  {
    name: "Golden Elixir Hair Oil",
    price: "68",
    color: "Gold",
    tag: "Hair Care",
    sizes: ["50ml", "100ml", "200ml"],
    description: "Brahmi, Amla & Bhringraj in cold-pressed coconut oil.",
  },
  {
    name: "Turmeric Glow Mask",
    price: "52",
    color: "Amber",
    tag: "Face Care",
    sizes: ["30g", "60g", "100g"],
    description: "Pure turmeric, sandalwood & raw honey face mask.",
  },
  {
    name: "Rose Hydra Mist",
    price: "45",
    color: "Rose",
    tag: "Face Care",
    sizes: ["50ml", "100ml", "150ml"],
    description: "Himalayan rose petal facial mist for hydration.",
  },
  {
    name: "Sandalwood Serum",
    price: "78",
    color: "Cream",
    tag: "Face Care",
    sizes: ["15ml", "30ml"],
    description: "Mysore sandalwood & saffron anti-aging serum.",
  },
  {
    name: "Ashwagandha Body Oil",
    price: "62",
    color: "Amber",
    tag: "Body Care",
    sizes: ["100ml", "200ml"],
    description: "Restorative body oil with Ashwagandha & sesame.",
  },
  {
    name: "Neem Purifying Cleanser",
    price: "38",
    color: "Green",
    tag: "Face Care",
    sizes: ["100ml", "200ml"],
    description: "Gentle cleanser with neem, tulsi & tea tree.",
  },
  {
    name: "Kumkumadi Night Elixir",
    price: "95",
    color: "Gold",
    tag: "Face Care",
    sizes: ["15ml", "30ml"],
    description: "Saffron & 16 precious herbs for luminous skin.",
  },
  {
    name: "Hibiscus Hair Mask",
    price: "48",
    color: "Rose",
    tag: "Hair Care",
    sizes: ["150g", "250g"],
    description: "Deep conditioning with hibiscus, henna & fenugreek.",
  },
  {
    name: "Vetiver Cooling Gel",
    price: "42",
    color: "Green",
    tag: "Body Care",
    sizes: ["100ml", "200ml"],
    description: "Soothing gel with vetiver, aloe & cucumber.",
  },
  {
    name: "Saffron Brightening Cream",
    price: "72",
    color: "Gold",
    tag: "Face Care",
    sizes: ["30g", "50g"],
    description: "Kashmiri saffron & licorice root day cream.",
  },
  {
    name: "Triphala Detox Mask",
    price: "46",
    color: "Amber",
    tag: "Face Care",
    sizes: ["50g", "100g"],
    description: "Purifying clay mask with Triphala & rose water.",
  },
  {
    name: "Jasmine Body Butter",
    price: "55",
    color: "Cream",
    tag: "Body Care",
    sizes: ["100g", "200g"],
    description: "Rich body butter with jasmine, shea & kokum.",
  },
  {
    name: "Bhringraj Hair Tonic",
    price: "58",
    color: "Green",
    tag: "Hair Care",
    sizes: ["100ml", "200ml"],
    description: "Scalp treatment with Bhringraj & peppermint.",
  },
  {
    name: "Chandan Face Mist",
    price: "40",
    color: "Cream",
    tag: "Face Care",
    sizes: ["50ml", "100ml"],
    description: "Calming toner with sandalwood & vetiver.",
  },
  {
    name: "Manjistha Glow Serum",
    price: "65",
    color: "Rose",
    tag: "Face Care",
    sizes: ["15ml", "30ml"],
    description: "Manjistha & pomegranate for even-toned radiance.",
  },
  {
    name: "Amla Hair Serum",
    price: "52",
    color: "Green",
    tag: "Hair Care",
    sizes: ["30ml", "60ml"],
    description: "Lightweight serum with Amla & argan oil.",
  },
  {
    name: "Lotus Eye Cream",
    price: "68",
    color: "Rose",
    tag: "Face Care",
    sizes: ["15g", "30g"],
    description: "Lotus extract & cucumber for delicate eye area.",
  },
  {
    name: "Kesar Glow Body Oil",
    price: "85",
    color: "Gold",
    tag: "Body Care",
    sizes: ["100ml", "200ml"],
    description: "Premium saffron, almond & jojoba body oil.",
  },
  {
    name: "Tulsi Clarifying Toner",
    price: "36",
    color: "Green",
    tag: "Face Care",
    sizes: ["100ml", "200ml"],
    description: "Holy basil & green tea balancing toner.",
  },
  {
    name: "Shikakai Shampoo Bar",
    price: "28",
    color: "Amber",
    tag: "Hair Care",
    sizes: ["75g", "100g"],
    description: "Zero-waste bar with Shikakai, Reetha & Amla.",
  },
  {
    name: "Moringa Body Lotion",
    price: "45",
    color: "Green",
    tag: "Body Care",
    sizes: ["200ml", "400ml"],
    description: "Lightweight daily lotion with Moringa & aloe.",
  },
  {
    name: "Bakuchi Anti-Age Oil",
    price: "88",
    color: "Amber",
    tag: "Face Care",
    sizes: ["15ml", "30ml"],
    description: "Natural retinol alternative from Babchi seeds.",
  },
  {
    name: "Mogra Hand Cream",
    price: "32",
    color: "Cream",
    tag: "Body Care",
    sizes: ["50g", "100g"],
    description: "Arabian jasmine & shea butter hand cream.",
  },
  {
    name: "Haldi Ubtan Scrub",
    price: "42",
    color: "Gold",
    tag: "Body Care",
    sizes: ["150g", "300g"],
    description: "Traditional turmeric & gram flour bridal scrub.",
  },
  {
    name: "Reetha Hair Wash",
    price: "35",
    color: "Amber",
    tag: "Hair Care",
    sizes: ["200ml", "400ml"],
    description: "Gentle soapnut cleanser with Shikakai & hibiscus.",
  },
  {
    name: "Aloe Vera Gel",
    price: "28",
    color: "Green",
    tag: "Body Care",
    sizes: ["200ml", "400ml"],
    description: "Pure aloe vera gel for face, body & hair.",
  },
  {
    name: "Ratrani Night Cream",
    price: "62",
    color: "Cream",
    tag: "Face Care",
    sizes: ["30g", "50g"],
    description: "Night jasmine & almond restorative cream.",
  },
  {
    name: "Nagarmotha Body Mist",
    price: "48",
    color: "Amber",
    tag: "Body Care",
    sizes: ["100ml", "200ml"],
    description: "Earthy aromatic mist with Cyprus & vetiver.",
  },
  {
    name: "Methi Hair Pack",
    price: "38",
    color: "Amber",
    tag: "Hair Care",
    sizes: ["100g", "200g"],
    description: "Protein-rich fenugreek treatment for strong hair.",
  },
  {
    name: "Parijat Lip Balm",
    price: "22",
    color: "Rose",
    tag: "Face Care",
    sizes: ["10g", "15g"],
    description: "Night jasmine, beeswax & ghee lip balm.",
  },
];
